version: "3.2"

services:
  webb:
    image: node:10
    volumes:
      - .:/srv
    working_dir: /srv
    restart: unless-stopped
    command: /bin/sh -c "npm i && node index.js --port=${WEBB_PORT}"
